import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Mybutton from "@/components/Mybutton";
import { Suspense } from "react";
import Loading from '@/app/[locale]/loading';
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/src/i18n/rounting";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href={"/about"}>About</Link>
        <Link href={"/"}>Home</Link>
        <Link href={"/contact"}>Contact</Link>
        <Suspense fallback={<Loading />}>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
